### ISSUE TITLE
Issue trying to run it

### ISSUE THREAD

**Issue by ghost** [ralfstx/angular2-renderer-example#2]
Hello, thank you for publishing this guys. 
Trying to run the step to run the install  and get tones of issue.
Any idea on how to get this running?
![screen shot 2017-09-13 at 18 06 17](https://user-images.githubusercontent.com/10134758/30390548-5b96e5a2-98ae-11e7-842c-eb40c952d11d.png)

**Comment by ghost** [comment]
My debug log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 silly lifecycle @~prestart: no script for prestart, continuing
7 info lifecycle @~start: @
8 verbose lifecycle @~start: unsafe-perm in lifecycle true
9 verbose lifecycle @~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/christarasovs/Desktop/Projects/angular2-renderer-example/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle @~start: CWD: /Users/christarasovs/Desktop/Projects/angular2-renderer-example
11 silly lifecycle @~start: Args: [ '-c', 'tsc && node dist/app/boot.js' ]
12 silly lifecycle @~start: Returned: code: 2  signal: null
13 info lifecycle @~start: Failed to exec start script
14 verbose stack Error: @ start: `tsc && node dist/app/boot.js`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @
16 verbose cwd /Users/christarasovs/Desktop/Projects/angular2-renderer-example
17 error Darwin 16.0.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
19 error node v6.11.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error @ start: `tsc && node dist/app/boot.js`
22 error Exit status 2
23 error Failed at the @ start script 'tsc && node dist/app/boot.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc && node dist/app/boot.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
